* Change the SOURCE logic to continue if one of the sources does not exist.
* Don't use " around VERSIONLIST.

diff --git a/src/builder/create-updates b/src/builder/create-updates
--- a/src/builder/create-updates
+++ b/src/builder/create-updates
@@ -70,70 +70,68 @@ do
 	SOURCEDIR="${RELEASEDIR}/evoke/${SOURCE}"
 	if [ ! -f "${SOURCEDIR}/trackfile" ] ; then
 		echo "Source does not exist"
-		exit 3
 	else
 		SOURCE_TRACKFILE="$(grep -a ^F: ${SOURCEDIR}/trackfile)"
-	fi
+		for filespec in ${DEST_TRACKFILE}
+		do
+			FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
+			DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
+			SOURCEFILE="${SOURCEDIR}/${FILENAME}"
+			DESTFILE="${DESTDIR}/${FILENAME}"
+			if [ -f "${SOURCEFILE}" ] ; then
+				SOURCEHASH="$(echo "${SOURCE_TRACKFILE}" | grep ${FILENAME} | cut -d : -f 3)"
+				REALHASH="$(sha256 -q "${SOURCEFILE}")"
+				if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
 
-	for filespec in ${DEST_TRACKFILE}
-	do
-		FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
-		DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
-		SOURCEFILE="${SOURCEDIR}/${FILENAME}"
-		DESTFILE="${DESTDIR}/${FILENAME}"
-		if [ -f "${SOURCEFILE}" ] ; then
-			SOURCEHASH="$(echo "${SOURCE_TRACKFILE}" | grep ${FILENAME} | cut -d : -f 3)"
-			REALHASH="$(sha256 -q "${SOURCEFILE}")"
-			if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
+					case "${SOURCEFILE}" in
+						*.gz)
+							mkdir -p "${DECOMDIR}"
+							gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
+							RFILE="${DECOMDIR}/${SOURCEHASH}"
+						;;
+						*)
+							RFILE="${SOURCEFILE}"
+						;;
+					esac
 
-				case "${SOURCEFILE}" in
-					*.gz)
-						mkdir -p "${DECOMDIR}"
-						gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
-						RFILE="${DECOMDIR}/${SOURCEHASH}"
-					;;
-					*)
-						RFILE="${SOURCEFILE}"
-					;;
-				esac
+					case "${DESTFILE}" in
+						*.gz)
+							mkdir -p "${DECOMDIR}"
+							gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
+							DFILE="${DECOMDIR}/${DESTHASH}"
+						;;
+						*)
+							DFILE="${DESTFILE}"
+						;;
+					esac
 
-				case "${DESTFILE}" in
-					*.gz)
-						mkdir -p "${DECOMDIR}"
-						gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
-						DFILE="${DECOMDIR}/${DESTHASH}"
-					;;
-					*)
-						DFILE="${DESTFILE}"
-					;;
-				esac
-
-				PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
-				mkdir -p ${PATCHDIR}/${DESTHASH}/
-				bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
-				mkdir -p "${TESTDIR}"
-				bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
-				case "${DESTFILE}" in
-					*.gz)
-						mkdir -p "${DECOMDIR}"
-						rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
-						gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
-						mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
-					;;
-					*.bz2)
-					;;
-					*)
-						RFILE="${FILENAME}"
-					;;
-				esac
-				REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
-				if [ "${REALHASH}" != "${DESTHASH}" ] ; then
-					echo "Patch failed"
-					exit 4
+					PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
+					mkdir -p ${PATCHDIR}/${DESTHASH}/
+					bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
+					mkdir -p "${TESTDIR}"
+					bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
+					case "${DESTFILE}" in
+						*.gz)
+							mkdir -p "${DECOMDIR}"
+							rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
+							gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
+							mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
+						;;
+						*.bz2)
+						;;
+						*)
+							RFILE="${FILENAME}"
+						;;
+					esac
+					REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
+					if [ "${REALHASH}" != "${DESTHASH}" ] ; then
+						echo "Patch failed"
+						exit 4
+					fi
 				fi
 			fi
-		fi
-	done
+		done
+	fi
 	shift
 done
 
