Merge /trunk r630:657 to /branches/releases/0.1/r1
r657 (heliocentric) {

	* Fix the versionlist logic again, hopefully for the last time.

}

r656 (heliocentric) {

	* Make sure we create an empty fstab, because dumpfs, fsck, and mount complain if the file doesn't exist.. for some reason.

}

r655 (heliocentric) {

	* Fix a bug where $@ wasn't surrounded by ", so it wasn't expanding properly.

}

r654 (heliocentric) {

	* Add unmount support to update, so if we choose the destdir from the list, it will get unmounted properly.

}

r653 (heliocentric) {

	AQA from MFRT run number: de78b4ba-46b0-4e1a-8655-f3d9578c01d4

	* Make sure we check if dump/swap/entropy are empty before passing to mounter.

}

r652 (heliocentric) {

	AQA from MFRT run number: de78b4ba-46b0-4e1a-8655-f3d9578c01d4

	* Fix bug where lsvol wasn't working correctly on 6.4 due to the geom type being 'GPT' instead of 'PART'

}

r651 (heliocentric) {

	* Remove gpart from the list, and change geom to geli.

}

r650 (heliocentric) {

	* Finish the geomlist support in dynamic.sh, and add geomlist to the '8' target.

}

r649 (heliocentric) {

	* Remove the kernels directory.

}

r648 (heliocentric) {

	* Move the kernel configs to the targets directory structure, and make sure build.sh and dynamic.sh understand it.

}

r647 (heliocentric) {

	* Add a 'geomlist' file, which are a list of hardlinks to the geli binary. Why geli? because geli is the only binary we explicitly need.

}

r646 (heliocentric) {

	* oops, missed a directory.

}

r645 (heliocentric) {

	* Add the directory tree where target specific files are stored.

}

r644 (heliocentric) {

	* small bug in versionlist, I forgot how sh handles ;.

}

r643 (heliocentric) {

	* Add support for lsvol to resolve device node names to ufs-style geom labels.

}

r642 (heliocentric) {

	* Remove the duplicates in the lsvol output, as mounter can handle boot- prefixed protocols now.

}

r641 (heliocentric) {

	* Add dumpfs so we can start using ufs labels correctly.

}

r640 (heliocentric) {

	* Same bug, but locally.

}

r639 (heliocentric) {

	* Generalize mounter's tag support, as there may be more then just boot-

	* Fix a typo that prevented build.sh from properly appending on the mirrors.

}

r638 (heliocentric) {

	* Fix a bug where menu was not preserving argument boundaries when called as an external command.

	* Fix a bug where mounter was unable to understand boot-ufs or boot-msdosfs, even though they are perfectly valid.

}

r637 (heliocentric) {

	* Break the update menu loop out of the conditional for the destination directory.

}

r636 (heliocentric) {

	* Make menu the default command for update.

}

r635 (heliocentric) {

	* Add the activate menu entry, and add a stub for the function.

}

r634 (heliocentric) {

	* Add error detection to menu, and allow a third operand, which does 'special' menu entries with letters instead of numbers.

}

r633 (heliocentric) {

	* Add the BIN-UPDATES to the iso image, for this test.

}

r632 (heliocentric) {

	* Add the menu drawing logic, quit, and back.

}

r631 (heliocentric) {

	* Make sure we specify the origin revision in the description.

}

diff --git a/0.1/r1/share/bin/update b/0.1/r1/share/bin/update
--- a/0.1/r1/share/bin/update
+++ b/0.1/r1/share/bin/update
@@ -49,6 +49,13 @@ if [ ! -d "${TMPDIR}" ] ; then
 	TMPDIR="/tmp"
 fi
 
+if [ ! -d "${EVOKE_MNTDIR}" ] ; then
+	EVOKE_MNTDIR="/media"
+	mkdir -p "${EVOKE_MNTDIR}"
+fi
+
+GLOBAL_ERRORCODE="0"
+
 apply_patch() {
 	PATCHFILE="${1}"
 	SOURCEFILE="${2}"
@@ -134,7 +141,7 @@ real_update() {
 		echo "The update utility will attempt to keep the total size of files downloaded to a"
 		echo "minimum, where possible."
 		echo ""
-		echo "In the worst case, update will download ${BYTECOUNT} bytes (~ ${MB}MB)"
+		echo "In the worst case, update will download ${BYTECOUNT} bytes (~ ${MB}M)"
 		read -p "Continue? [Y/n]: " PROMPT
 	else
 		PROMPT="y"
@@ -384,20 +391,101 @@ vecho() {
 getfile() {
 	phttpget "${SERVER}" "${FILESPEC}/${1}" 2>${DEVICES}/null
 }
+
+activater() {
+	echo "Does not exist yet"
+}
+
 update_menu() {
+	if [ "${1}" != "" ] ; then
+		local DESTDIR="${1}"
+	fi
+
+	if [ ! -d "${DESTDIR}" ] ; then
+		local DESTDIR="${EVOKE_MNTDIR}/$(dd if=/dev/random bs=4m ocunt=1 2>/dev/null | sha256 -q)"
+		mkdir -p "${DESTDIR}"
+
+		local CHOICE=$(menu "Boot filesystem" "$(mounter list boot-ufs)" "q:Quit")
+		if [ "${CHOICE}" != "" ] ; then
+			case "${CHOICE}" in
+				Quit)
+					echo "No destination directory specified!"
+					GLOBAL_ERRORCODE="65"
+					return
+
+				;;
+				*)
+					mounter "boot-ufs:${CHOICE}" "${DESTDIR}"
+				;;
+			esac
+		else
+			echo "No destination directory specified!"
+			GLOBAL_ERRORCODE="65"
+			return
+		fi
+	fi
+
 	. $(command -v menu)
 	find_mirror "evoke/misc/versionlist" "${TEMPDIR}/versionlist"
+
 	if [ -f "${TEMPDIR}/versionlist" ] ; then
 		while [ 1 != 2 ]
 		do
 			unset BRANCH
+			unset RESULT
 			unset REVISIONS
 			unset REVISION
-			clear
-			BRANCH=$(menu "Branch" "$(cut -d "/" -f 1 ${TEMPDIR}/versionlist | sort -r | uniq | grep -v ^$)")
-			REVISIONS="$(awk -F "/" -v branch="${BRANCH}" '{ if ($1 == branch) { print $2; }; }' ${TEMPDIR}/versionlist | sort -r | grep -v ^$)"
-			BRANCH=$(menu "Revision" "${REVISIONS}")
+			BRANCH=$(menu "Branch" "$(cut -d "/" -f 1 ${TEMPDIR}/versionlist | sort -r | uniq | grep -v ^$)" "$(printf "a:Activate\nq:Quit")")
+			if [ "${BRANCH}" != "" ] ; then
+				case "${BRANCH}" in
+					Quit)
+						break
+					;;
+					Activate)
+						activater
+						break
+					;;
+					*)
+						while [ 1 != 2 ]
+						do
+							unset RESULT
+							unset REVISIONS
+							unset REVISION
+
+							REVISIONS="$(awk -F "/" -v branch="${BRANCH}" '{ if ($1 == branch) { print $2; }; }' ${TEMPDIR}/versionlist | sort -r | grep -v ^$)"
+							REVISION=$(menu "Revision" "${REVISIONS}" "$(printf "a:Activate\nb:Back\nq:Quit")")
+							if [ "${REVISION}" != "" ] ; then
+								case "${REVISION}" in
+									Quit)
+										break 2
+									;;
+									Activate)
+										activater
+										break
+									;;
+									Back)
+										break
+									;;
+									*)
+										VERSION="${BRANCH}/${REVISION}"
+										real_update "${DESTDIR}" "${VERSION}"
+									;;
+								esac
+							else
+								echo "Revision not found! - Press any key to continue" 
+								read RESULT
+							fi
+						done
+					;;
+				esac
+			else
+				echo "Branch not found! - Press any key to continue" 
+				read RESULT
+			fi
 		done
+		if [ "${CHOICE}" != "" ] ; then
+			mounter umount "${DESTDIR}"
+		fi
 	fi
 }
 
@@ -447,16 +535,20 @@ update() {
 	fi
 
 	case "${1}" in
-		[mM][eE][nN][uU])
-			update_menu
-		;;
 		[iI][nN][sS][tT][aA][lL][lL])
 			if [ "${3}" != "" ] ; then
 				real_update "${2}" "${3}" 2>&1
 			fi
 		;;
+		[mM][eE][nN][uU])
+			update_menu "${2}"
+		;;
+		*)
+			update_menu "${2}"
+		;;
 	esac
 	rm -r ${SCRATCHDIR}
+	exit "${GLOBAL_ERRORCODE}"
 }
 
 update $@
