* Move everything over to the new Hierarchy, while simultaneously cleaning up files.

diff --git a/src/share/bin/dhclient-script b/src/share/bin/dhclient-script
--- a/src/share/bin/dhclient-script
+++ b/src/share/bin/dhclient-script
@@ -19,6 +19,14 @@
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
 #
+if [ ! -c "${DEVICES}/null" ] ; then
+	if [ -c "/dev/null" ] ; then
+		DEVICES=/dev
+	else
+		echo "Error, no device nodes found"
+		exit 1
+	fi
+fi
 
 ARP=arp
 AWK=awk
@@ -53,7 +61,7 @@ check_hostname() {
 arp_flush() {
 	arp -an -i $interface | \
 		sed -n -e 's/^.*(\(.*\)) at .*$/arp -d \1/p' | \
-		sh >/dev/null 2>&1
+		sh >${DEVICES}/null 2>&1
 }
 
 delete_old_address() {
@@ -75,8 +83,8 @@ add_new_address() {
 
 delete_old_alias() {
 	if [ -n "$alias_ip_address" ]; then
-		$IFCONFIG $interface inet -alias $alias_ip_address > /dev/null 2>&1
-		#route delete $alias_ip_address $LOCALHOST > /dev/null 2>&1
+		$IFCONFIG $interface inet -alias $alias_ip_address > ${DEVICES}/null 2>&1
+		#route delete $alias_ip_address $LOCALHOST > ${DEVICES}/null 2>&1
 	fi
 }
 
@@ -114,7 +122,7 @@ fill_classless_routes() {
 }
 
 delete_old_routes() {
-	#route delete "$old_ip_address" $LOCALHOST >/dev/null 2>&1
+	#route delete "$old_ip_address" $LOCALHOST >${DEVICES}/null 2>&1
 	if [ -n "$old_classless_routes" ]; then
 		fill_classless_routes "$old_classless_routes"
 		set $classless_routes
@@ -127,7 +135,7 @@ delete_old_routes() {
 
 	for router in $old_routers; do
 		if [ $if_defaultroute = x -o $if_defaultroute = $interface ]; then
-			route delete default $route >/dev/null 2>&1
+			route delete default $route >${DEVICES}/null 2>&1
 		fi
 	done
 
@@ -143,7 +151,7 @@ delete_old_routes() {
 }
 
 add_new_routes() {
-	#route add $new_ip_address $LOCALHOST >/dev/null 2>&1
+	#route add $new_ip_address $LOCALHOST >${DEVICES}/null 2>&1
 
 	# RFC 3442: If the DHCP server returns both a Classless Static
 	# Routes option and a Router option, the DHCP client MUST ignore
@@ -171,9 +179,9 @@ add_new_routes() {
 
 	for router in $new_routers; do
 		if [ "$new_ip_address" = "$router" ]; then
-			route add default -iface $router >/dev/null 2>&1
+			route add default -iface $router >${DEVICES}/null 2>&1
 		else
-			route add default $router >/dev/null 2>&1
+			route add default $router >${DEVICES}/null 2>&1
 		fi
 		# 2nd and subsequent default routers error out, so explicitly
 		# stop processing the list after the first one.
@@ -197,7 +205,7 @@ add_new_resolv_conf() {
 	# thus broke the script. This code creates the resolv.conf if either
 	# are provided.
 
-	local tmpres=/var/run/resolv.conf.${interface}
+	local tmpres=${N_RUNDIR}/resolv.conf.${interface}
 	rm -f $tmpres
 
 	if [ -n "$new_domain_name" ]; then
@@ -211,8 +219,8 @@ add_new_resolv_conf() {
 	fi
 
 	if [ -f $tmpres ]; then
-		if [ -f /cfg/resolv.conf.tail ]; then
-			cat /cfg/resolv.conf.tail >>$tmpres
+		if [ -f /config/resolv.conf.tail ]; then
+			cat /config/resolv.conf.tail >>$tmpres
 		fi
 
 		# When resolv.conf is not changed actually, we don't
@@ -220,24 +228,24 @@ add_new_resolv_conf() {
 		# If /usr is not mounted yet, we cannot use cmp, then
 		# the following test fails.  In such case, we simply
 		# ignore an error and do update resolv.conf.
-		if cmp -s $tmpres /cfg/resolv.conf; then
+		if cmp -s $tmpres /config/resolv.conf; then
 			rm -f $tmpres
 			return 0
-		fi 2>/dev/null
+		fi 2>${DEVICES}/null
 
 		# In case (e.g. during OpenBSD installs) /etc/resolv.conf
 		# is a symbolic link, take care to preserve the link and write
 		# the new data in the correct location.
 
-		if [ -f /cfg/resolv.conf ]; then
-			cat /cfg/resolv.conf > /tmp/lib/resolv.conf.save
+		if [ -f /config/resolv.conf ]; then
+			cat /config/resolv.conf > ${N_LIBDIR}/resolv.conf.save
 		fi
-		cat $tmpres > /tmp/lib/resolv.conf
+		cat $tmpres > ${N_LIBDIR}/resolv.conf
 		rm -f $tmpres
 
 		# Try to ensure correct ownership and permissions.
-		chown -RL root:wheel /tmp/lib/resolv.conf
-		chmod -RL 644 /tmp/lib/resolv.conf
+		chown -RL root:wheel ${N_LIBDIR}/resolv.conf
+		chmod -RL 644 ${N_LIBDIR}/resolv.conf
 
 		return 0
 	fi
@@ -248,8 +256,8 @@ add_new_resolv_conf() {
 # Must be used on exit.   Invokes the local dhcp client exit hooks, if any.
 exit_with_hooks() {
 	exit_status=$1
-	if [ -f /cfg/dhclient-exit-hooks ]; then
-		. /cfg/dhclient-exit-hooks
+	if [ -f /config/dhclient-exit-hooks ]; then
+		. /config/dhclient-exit-hooks
 	fi
 	# probably should do something with exit status of the local script
 	exit $exit_status
@@ -260,9 +268,9 @@ exit_with_hooks() {
 #
 
 # Invoke the local dhcp client enter hooks, if they exist.
-if [ -f /cfg/dhclient-enter-hooks ]; then
+if [ -f /config/dhclient-enter-hooks ]; then
 	exit_status=0
-	. /cfg/dhclient-enter-hooks
+	. /config/dhclient-enter-hooks
 	# allow the local script to abort processing of this state
 	# local script must set exit_status variable to nonzero.
 	if [ $exit_status -ne 0 ]; then
@@ -279,7 +287,7 @@ fi
 case $reason in
 MEDIUM)
 	eval "$IFCONFIG $interface $medium"
-	eval "$IFCONFIG $interface inet -alias 0.0.0.0 $medium" >/dev/null 2>&1
+	eval "$IFCONFIG $interface inet -alias 0.0.0.0 $medium" >${DEVICES}/null 2>&1
 	sleep 1
 	;;
 
@@ -326,8 +334,8 @@ EXPIRE|FAIL)
 	fi
 	# XXX Why add alias we just deleted above?
 	add_new_alias
-	if [ -f /cfg/resolv.conf.save ]; then
-		cat /cfg/resolv.conf.save > /tmp/lib/resolv.conf
+	if [ -f /config/resolv.conf.save ]; then
+		cat /config/resolv.conf.save > ${N_LIBDIR}/resolv.conf
 	fi
 	;;
 
