* Add 'create' functionality to sysconfig, as well as printf/uuid to portlist and a wiki page describing it.

diff --git a/src/share/bin/sysconfig b/src/share/bin/sysconfig
--- a/src/share/bin/sysconfig
+++ b/src/share/bin/sysconfig
@@ -34,34 +34,95 @@ if [ ! -c "${DEVICES}/null" ] ; then
 		exit 1
 	fi
 fi
+
+if [ ! -d "${TMPDIR}" ] ; then
+	TMPDIR=/tmp
+fi
+
+SCRATCHDIR="${TMPDIR}/sctemp/$(dd if=${DEVICES}/random bs=4m count=1 2>${DEVICES}/null | md5 -q )"	
+mkdir -p "${SCRATCHDIR}"
+
+if [ ! -d "${N_SYSCFG}" ] ; then
+	N_SYSCFG="/tmp/sysconfig"
+	mkdir -p "${N_SYSCFG}"
+fi
+
 usage () {
 }
-checknvram () {
-	TYPE=$(stat -f "%HT" "${1}")
+
+prepnvram () {
+	TYPE=$(stat -f "%HT" "${DEVICES}/${1}")
 	case "${TYPE}" in
 		Character*)
-			echo "test"
+			SC_GEOM=$(sysctl -b kern.geom.conftxt | grep -a ${1})
+			SC_SECTORSIZE=$(echo ${SC_GEOM} | cut -d " " -f 5)
+			dd if=${DEVICES}/${1} of=${SCRATCHDIR}/headsect bs=${SC_SECTORSIZE} count=1 conv=sync fillchar=" " 2>/dev/null
+			dd if=${SCRATCHDIR}/headsect of=${SCRATCHDIR}/hash bs=64 count=1 conv=sync fillchar=" " 2>/dev/null
+			dd if=${SCRATCHDIR}/headsect of=${SCRATCHDIR}/header bs=64 skip=1 conv=sync fillchar=" " 2>/dev/null
+			HEADERSIZE="$(stat -f '%z' ${SCRATCHDIR}/header)"
+		;;
+		*)
+			echo "Not a character device"
+			exit 2
 		;;
 	esac
 }
 
 case "${1}" in
+	[vV][eE][rR][iI][fF][yY])
+		prepnvram "${2}"
+		RHASH=$(sha256 -q ${SCRATCHDIR}/header)
+		HASH=$(cat ${SCRATCHDIR}/hash)
+		if [ "${RHASH}" != "${HASH}" ] ; then
+			echo "failed"
+			exit 3
+		else
+			echo "passed"
+			exit 0
+		fi
+	;;
 	[eE][xX][tT][rR][aA][cC][tT])
 		EXTRACTPOINT="${3}"
-		checknvram "${2}"
+		prepnvram "${2}"
+		set | grep ^SC
 	;;
 	[lL][iI][sS][tT])
 		mounter list nvram
 	;;
 	[cC][lL][eE][aA][rR])
-		checknvram "${2}"
-		#dd if=/dev/zero bs=512 of=${DEVICES}/${2} count=1
-		#dd if=/dev/urandom bs=512 seek=512 of=${DEVICES}/${2}
+		prepnvram "${2}"
 	;;
 	[cC][rR][eE][aA][tT][eE])
-		
+		prepnvram "${2}"
+		unset break
+		until [ "${break}" = "yes" ]
+		do
+			read -p "Description: " LONGDESC
+			if [ "${LONGDESC}" != "" ] ; then
+				break="yes"
+			else
+				echo "Please input a long description"
+			fi
+		done
+		unset break
+		until [ "${break}" = "yes" ]
+		do
+			read -p "Length of the config log: " CONFIGLOG
+			if [ "${CONFIGLOG}" != "" ] ; then
+				break="yes"
+			else
+				CONFIGLOG=8
+				break="yes"
+			fi
+		done
+		UUID=$(uuid -v 4)
+		printf "\nlog=${CONFIGLOG}\nuuid=${UUID}\ndescription=${LONGDESC}\n" | dd bs=${HEADERSIZE} count=1 of=${SCRATCHDIR}/header conv=sync 2>/dev/null
+		sha256 -q ${SCRATCHDIR}/header | dd bs=64 count=1 of=${SCRATCHDIR}/hash fillchar=" " conv=sync 2>/dev/null
+		cat ${SCRATCHDIR}/hash ${SCRATCHDIR}/header >${SCRATCHDIR}/headsect
 	;;
 	*)
 		usage
 	;;
 esac
+
+#rm -r ${SCRATCHDIR}
