* Add part of the 'commit' command to sysconfig.

diff --git a/src/share/bin/sysconfig b/src/share/bin/sysconfig
--- a/src/share/bin/sysconfig
+++ b/src/share/bin/sysconfig
@@ -39,7 +39,7 @@ if [ ! -d "${TMPDIR}" ] ; then
 	TMPDIR=/tmp
 fi
 
-export SCRATCHDIR="${TMPDIR}/sctemp/$(dd if=${DEVICES}/random bs=4m count=1 2>${DEVICES}/null | md5 -q )"	
+export SCRATCHDIR="${TMPDIR}/sctemp/$(dd if=${DEVICES}/random bs=4m count=1 2>${DEVICES}/null | sha256 -q )"	
 mkdir -p "${SCRATCHDIR}"
 
 if [ ! -d "${N_SYSCFG}" ] ; then
@@ -54,31 +54,67 @@ prepsysconfig () {
 	TYPE=$(stat -f "%HT" "${DEVICES}/${1}")
 	case "${TYPE}" in
 		Character*)
-			SC_GEOM=$(sysctl -b kern.geom.conftxt | grep -a ${1})
-			SC_SECTORSIZE=$(echo ${SC_GEOM} | cut -d " " -f 5)
+			export SC_GEOM="$(sysctl -b kern.geom.conftxt | grep -a ${1})"
+			export SC_SECTORSIZE="$(echo ${SC_GEOM} | cut -d " " -f 5)"
 
 			# Since conftxt only reports the size in bytes of the geom, we have to divide it by the sector size and then remove a sector that is always used by the header.
-			SC_SECTORCOUNT=$(($(echo ${SC_GEOM} | cut -d " " -f 4) / ${SC_SECTORSIZE} - 1))
+			export SC_SECTORCOUNT="$(($(echo ${SC_GEOM} | cut -d " " -f 4) / ${SC_SECTORSIZE} - 1))"
 
 			# For ata/scsi this doesn't matter, but only reading in the partition once really helps USB thumb drives
-			dd if=${DEVICES}/${1} of=${SCRATCHDIR}/partition 2>/dev/null
-			dd if=${SCRATCHDIR}/partition of=${SCRATCHDIR}/headsect bs=${SC_SECTORSIZE} count=1 conv=sync fillchar=" " 2>/dev/null
-			dd if=${SCRATCHDIR}/headsect of=${SCRATCHDIR}/hash bs=64 count=1 conv=sync fillchar=" " 2>/dev/null
-			dd if=${SCRATCHDIR}/headsect of=${SCRATCHDIR}/header bs=64 skip=1 conv=sync fillchar=" " 2>/dev/null
+			dd if=${DEVICES}/${1} of=${SCRATCHDIR}/partition 2>${DEVICES}/null
+			dd if=${SCRATCHDIR}/partition of=${SCRATCHDIR}/headsect bs=${SC_SECTORSIZE} count=1 conv=sync fillchar=" " 2>${DEVICES}/null
+			dd if=${SCRATCHDIR}/headsect of=${SCRATCHDIR}/hash bs=64 count=1 conv=sync fillchar=" " 2>${DEVICES}/null
+			dd if=${SCRATCHDIR}/headsect of=${SCRATCHDIR}/header bs=64 skip=1 conv=sync fillchar=" " 2>${DEVICES}/null
 
 			# size of the header, in bytes
-			SC_HEADERSIZE="$(stat -f '%z' ${SCRATCHDIR}/header)"
+			export SC_HEADERSIZE="$(stat -f '%z' ${SCRATCHDIR}/header)"
 
 			if [ "$(verify_header)" = "passed" ] ; then
-
-				SC_UUID=$(grep -a ^uuid= ${SCRATCHDIR}/header | cut -d = -f 2)
-				SC_DESCRIPTION=$(grep -a ^description= ${SCRATCHDIR}/header | cut -d = -f 2)
-				SC_ENTRYSIZE=$(grep -a ^entrysize= ${SCRATCHDIR}/header | cut -d = -f 2)
-				SC_PADSIZE=$(grep -a ^pad= ${SCRATCHDIR}/header | cut -d = -f 2)
+				export SC_UUID="$(grep -a ^uuid= ${SCRATCHDIR}/header | cut -d = -f 2)"
+				export SC_DESCRIPTION="$(grep -a ^description= ${SCRATCHDIR}/header | cut -d = -f 2)"
+				export SC_ENTRYSIZE="$(grep -a ^entrysize= ${SCRATCHDIR}/header | cut -d = -f 2)"
+				export SC_PADSIZE="$(grep -a ^pad= ${SCRATCHDIR}/header | cut -d = -f 2)"
 
 				# the number of entries in the config log
-				SC_LOGSIZE=$(grep -a ^log= ${SCRATCHDIR}/header | cut -d = -f 2)
-				SC_ARRAYOFFSET=$((${SC_PADSIZE} + 1))
+				export SC_LOGSIZE="$(grep -a ^log= ${SCRATCHDIR}/header | cut -d = -f 2)"
+				export SC_ARRAYOFFSET="$((${SC_PADSIZE} + 1))"
+				export SC_TARBALLSIZE="$(( (${SC_ENTRYSIZE} * 512) - 74))"
+
+				export RECORDNUM=1
+				export TEMPOFFSET="${SC_ARRAYOFFSET}"
+
+				# anyone who's ever used a functional language will hate this, but it does what is intended.
+				# since bourne shell's looping facilities leave a lot to be desired, this saves us quite 
+				# a lot of time by doing the loop once.
+
+				export SC_CONSISTENT=$(until [ "${RECORDNUM}" -gt "${SC_LOGSIZE}" ]
+				do
+					mkdir -p ${SCRATCHDIR}/record${RECORDNUM}
+					dd if=${SCRATCHDIR}/partition of=${SCRATCHDIR}/record${RECORDNUM}/record bs=${SC_SECTORSIZE} count=${SC_ENTRYSIZE} skip=${TEMPOFFSET} conv=sync fillchar=" " 2>${DEVICES}/null
+					dd if=${SCRATCHDIR}/record${RECORDNUM}/record bs=1 count=64 conv=sync fillchar=" " of=${SCRATCHDIR}/record${RECORDNUM}/hash 2>${DEVICES}/null
+					dd if=${SCRATCHDIR}/record${RECORDNUM}/record bs=1 skip=64 count=10 conv=sync fillchar=" " of=${SCRATCHDIR}/record${RECORDNUM}/timestamp 2>${DEVICES}/null
+					dd if=${SCRATCHDIR}/record${RECORDNUM}/record bs=1 skip=74 conv=sync fillchar=" " of=${SCRATCHDIR}/record${RECORDNUM}/tarball.tgz 2>${DEVICES}/null
+					RHASH="$(cat ${SCRATCHDIR}/record${RECORDNUM}/timestamp ${SCRATCHDIR}/record${RECORDNUM}/tarball.tgz | sha256 -q)"
+					if [ "$(cat ${SCRATCHDIR}/record${RECORDNUM}/hash)" != "${RHASH}" ] ; then
+						touch ${SCRATCHDIR}/record${RECORDNUM}/failed
+					else
+						echo "$(${SCRATCHDIR}/record${RECORDNUM}/timestamp) ${RECORDNUM}"
+						touch ${SCRATCHDIR}/record${RECORDNUM}/passed
+					fi
+					rm ${SCRATCHDIR}/record${RECORDNUM}/record
+					TEMPOFFSET=$((${TEMPOFFSET} + ${SC_ENTRYSIZE}))
+					RECORDNUM=$((${RECORDNUM} + 1))
+				done | sort)
+				if [ "${SC_CONSISTENT}" = "" ] ; then
+					SC_CURRECORD="0"
+				else
+					SC_CURRECORD="$(echo ${SC_CONSISTENT} | head -n 1 | cut -d " " -f 2)"
+				fi
+				SC_NEXTRECORD="$((${SC_CURRECORD} + 1))"
+				if [ "${SC_NEXTRECORD}" -gt "${SC_LOGSIZE}" ] ; then
+					SC_NEXTRECORD="1"
+				fi
+				rm ${SCRATCHDIR}/partition
 			fi
 		;;
 		*)
@@ -114,12 +150,26 @@ case "${1}" in
 	[lL][iI][sS][tT])
 		mounter list sysconfig
 	;;
-	[cC][oO][mM][iI][tT])
+	[cC][oO][mM][mM][iI][tT])
 		prepsysconfig "${2}"
+		if [ ! -d "${3}" ] ; then
+			echo "Source is not a directory"
+			exit 4
+		fi
+		cd "${3}"
+		tar -cpf - * | gzip -9 >newrecord.tgz
+		if [ "$(stat -f '%z' ${SCRATCHDIR}/newrecord.tgz)" -gt "${SC_TARBALLSIZE}" ] ; then
+			echo "Error, config to large for partition"
+			exit 5
+		fi
+		dd if=${SCRATCHDIR}/newrecord.tgz of=${SCRATCHDIR}/newrecord bs=1 count=${SC_TARBALLSIZE} conv=sync 2>${DEVICES}/null
+		date +%s | dd of=${SCRATCHDIR}/newdate bs=10 count=1 conv=sync 2>${DEVICES}/null
+		cat ${SCRATCHDIR}/newdate ${SCRATCHDIR}/newrecord | sha256 -q | dd of=${SCRATCHDIR}/newhash bs=64 count=1 conv=sync 2>${DEVICES}/null
+		cat ${SCRATCHDIR}/newhash ${SCRATCHDIR}/newdate ${SCRATCHDIR}/newrecord
 	;;
 	[cC][lL][eE][aA][rR])
 		prepsysconfig "${2}"
-		dd if=${DEVICES}/zero of=${DEVICES}/${2} bs=${SC_SECTORSIZE} count=$((${SC_SECTORCOUNT} + 1)) 2>/dev/null
+		dd if=${DEVICES}/zero of=${DEVICES}/${2} bs=${SC_SECTORSIZE} count=$((${SC_SECTORCOUNT} + 1)) 2>${DEVICES}/null
 	;;
 	[cC][rR][eE][aA][tT][eE])
 		prepsysconfig "${2}"
@@ -154,10 +204,10 @@ case "${1}" in
 		# arraysize * array entries + header sector exactly.
 		SC_PADSIZE=$((${SC_SECTORCOUNT} % ${CONFIGLOG}))
 
-		printf "\nversion=1.0\nentrysize=${SC_ENTRYSIZE}\npad=${SC_PADSIZE}\nlog=${CONFIGLOG}\nuuid=${UUID}\ndescription=${LONGDESC}\n" | dd bs=${SC_HEADERSIZE} count=1 of=${SCRATCHDIR}/header conv=sync 2>/dev/null
-		sha256 -q ${SCRATCHDIR}/header | dd bs=64 count=1 of=${SCRATCHDIR}/hash fillchar=" " conv=sync 2>/dev/null
+		printf "\nversion=1.0\nentrysize=${SC_ENTRYSIZE}\npad=${SC_PADSIZE}\nlog=${CONFIGLOG}\nuuid=${UUID}\ndescription=${LONGDESC}\n" | dd bs=${SC_HEADERSIZE} count=1 of=${SCRATCHDIR}/header conv=sync 2>${DEVICES}/null
+		sha256 -q ${SCRATCHDIR}/header | dd bs=64 count=1 of=${SCRATCHDIR}/hash fillchar=" " conv=sync 2>${DEVICES}/null
 		cat ${SCRATCHDIR}/hash ${SCRATCHDIR}/header >${SCRATCHDIR}/headsect
-		cat ${SCRATCHDIR}/headsect | dd of=${DEVICES}/${2} bs=${SC_SECTORSIZE} count=1 2>/dev/null
+		cat ${SCRATCHDIR}/headsect | dd of=${DEVICES}/${2} bs=${SC_SECTORSIZE} count=1 2>${DEVICES}/null
 	;;
 	*)
 		usage
