* Move everything over to the new Hierarchy, while simultaneously cleaning up files.

diff --git a/trunk/src/share/bin/installer b/trunk/src/share/bin/installer
--- a/trunk/src/share/bin/installer
+++ b/trunk/src/share/bin/installer
@@ -24,10 +24,14 @@
 # POSSIBILITY OF SUCH DAMAGE.
 
 # $Id$
-	#
-    #
-if [ "${TMPDIR}" = "" ] ; then
-	export TMPDIR=/tmp/scratch
+
+if [ ! -c "${DEVICES}/null" ] ; then
+	if [ -c "/dev/null" ] ; then
+		DEVICES=/dev
+	else
+		echo "Error, no device nodes found"
+		exit 1
+	fi
 fi
 
 get_disk () {
@@ -35,8 +39,8 @@ get_disk () {
 }
 
 real_install () {
-	if [ -c /dev/label/trackfile ] ; then
-		CLEANFILE=$(grep -v ^# /dev/label/trackfile)
+	if [ -c ${DEVICES}/label/trackfile ] ; then
+		CLEANFILE=$(grep -v ^# ${DEVICES}/label/trackfile)
 		for i in $(echo ${CLEANFILE} | grep ^F)
 		do
 			echo "${i}"
diff --git a/trunk/src/share/bin/jailer b/trunk/src/share/bin/jailer
--- a/trunk/src/share/bin/jailer
+++ b/trunk/src/share/bin/jailer
@@ -26,9 +26,18 @@
 
 # $Id$
 
+if [ ! -c "${DEVICES}/null" ] ; then
+	if [ -c "/dev/null" ] ; then
+		DEVICES=/dev
+	else
+		echo "Error, no device nodes found"
+		exit 1
+	fi
+fi
+
 case "${1}" in
 	[mM][oO][uU][nN][tT])
-		if [ -c "/dev/${2}" ] ; then
+		if [ -c "${DEVICES}/${2}" ] ; then
 			sysctl -b kern.geom.conftxt | grep -aw ${2} |  awk '{
 				if ($2 == "BSD") {
 					if ($11 == "7") {
@@ -37,7 +46,7 @@ case "${1}" in
 				};
 			}'
 		else
-			echo "/dev/${2} is not a device node"  >&2 
+			echo "${DEVICES}/${2} is not a device node"  >&2 
 		fi
 	;;
 	[rR][uU][nN])
diff --git a/trunk/src/share/bin/verify b/trunk/src/share/bin/verify
--- a/trunk/src/share/bin/verify
+++ b/trunk/src/share/bin/verify
@@ -29,6 +29,16 @@
 # Set this so we can call this file again if a filename passed is a directory.
 BIN="$0"
 
+# Check for the existence of the DEVICES variable, and whether it's what we need. if not, fall back to /dev
+if [ ! -c "${DEVICES}/null" ] ; then
+	if [ -c "/dev/null" ] ; then
+		DEVICES=/dev
+	else
+		echo "Error, no device nodes found"
+		exit 1
+	fi
+fi
+
 # This works whether TRACKFILE is a device node, or a regular file.
 
 if [ ! -r "${TRACKFILE}" -o -d "${TRACKFILE}" ] ; then
@@ -58,13 +68,13 @@ do
 		do
 			# We always need the file's hash from the contents, so keep it out
 			# of the conditional
-			RHASH=$(${type} -q "${1}" 2>/dev/null)
+			RHASH=$(${type} -q "${1}" 2>${DEVICES}/null)
 			if [ "${WRITE}" = "yes" ] ; then
-				setextattr system ${type} ${RHASH} "${1}" 2>/dev/null
+				setextattr system ${type} ${RHASH} "${1}" 2>${DEVICES}/null
 			else
 				unset FHASH
 				if [ "${FHASH}" = "" ] ; then
-					FHASH=$(getextattr -q system ${type} "${1}" 2>/dev/null)
+					FHASH=$(getextattr -q system ${type} "${1}" 2>${DEVICES}/null)
 				fi
 				if [ "${RHASH}" != "${FHASH}" ] ; then
 					echo "${type} fail ${1}"					
