* Start new mounter, added basics of URI parsing.

diff --git a/trunk/src/share/bin/mounter b/trunk/src/share/bin/mounter
--- a/trunk/src/share/bin/mounter
+++ b/trunk/src/share/bin/mounter
@@ -174,6 +174,123 @@ old_mounter () {
 		;;
 	esac
 }
+
+new_mounter () {
+	if [ "${1}" != "" ] ; then
+		if [ "$( echo ${1} | grep :)" != "" ] ; then
+			# Since a : is in the first argument, we treat it as a proto:source, rather then a command
+
+			M_PROTO=$(echo "${1}" | cut -d : -f 1)
+			M_SOURCE=$(echo "${1}" | cut -d : -f 2-60)
+			if [ "$( echo ${M_PROTO} | grep +)" != "" ] ; then
+				# Since it's in the form proto+transport, set M_TRANSPORT first, then M_PROTO to the 'real' protocol.
+				M_TRANSPORT=$(echo "${M_PROTO}" | cut -d + -f 2)
+				M_PROTO=$(echo "${M_PROTO}" | cut -d + -f 1)
+			fi
+			case "${M_SOURCE}" in
+				//*)
+					M_SOURCE=$(echo ${M_SOURCE} | cut -b 3-400 )
+					M_TYPE="URI"
+					if [ "$( echo ${M_SOURCE} | grep /)" != "" ] ; then
+						M_FILE=/$(echo ${M_SOURCE} | cut -d / -f 2-400)
+					fi
+				;;
+				/*)
+					M_TYPE="FILE"
+				;;
+				[aA][lL][lL])
+					M_TYPE="ALL"
+				;;
+				*)
+					M_TYPE="GEOM"
+				;;
+			esac
+
+			echo "proto=${M_PROTO}"
+			echo "transport=${M_TRANSPORT}"
+			echo "type=${M_TYPE}"
+			echo "username=${M_USERNAME}"
+			echo "password=${M_PASSWORD}"
+			echo "host=${M_HOST}"
+			echo "port=${M_PORT}"
+			echo "file=${M_FILE}"
+		else
+			mounter_command $*
+		fi 
+	fi
+}
+
+mounter_command () {
+	case "${1}" in
+		[uU][nN][mM][oO][uU][nN][tT])
+			mount | awk -v MOUNTPOINT=$2 '{
+				mount=$3
+				devicenode=$1
+				if (mount == MOUNTPOINT) {
+					if (devicenode ~ /fuse/) {
+						system("umount " devicenode);
+						close("umount " devicenode);
+					} else {
+						system("umount " mount);
+						close ("umount " mount);
+					}
+				}
+			}'
+		;;
+	  	[lL][iI][sS][tT])
+	
+		# We silently drop if someone types 'mounter list', however, 
+		# if the third argument is a directory, we assume the user 
+		# wants to automount volumes into that directory. For example, 
+		# mounter list ufs /media will mount all ufs partitions into 
+		# /media named after their geom name. ie, /media/da0s1a, etc.
+			case "${2}" in
+				[Ff][sS])
+					lsvfs | awk '{ 
+						if (NR > 2) 
+						{
+							if ($3 != "synthetic" && $3 != "loopback" && $1 != "tmpfs") {
+								print $1 
+							}
+						}
+					}'
+					echo "boot-ufs"
+					for fuse in wdfs sshfs curlftpfs ntfs-3g
+					do
+						command -v ${fuse} >${DEVICES}/null 
+						if [ "$?" != "127" ] ; then
+							case "${fuse}" in
+								sshfs) echo ssh ;;
+								ntfs-3g) echo ntfs ;;
+								curlftpfs) echo ftp ;;
+								wdfs) echo webdav ;;
+							esac
+						fi
+					done
+					
+				;;
+
+				*)
+					if [ "${2}" != "" ] ; then
+						for i in $(lsvol | grep ^${2}:)
+						do
+							DEVNODE=$(echo ${i} | cut -d : -f 2)
+#							if [ -d "${3}" ] ; then
+#								mkdir -p ${3}/${i}
+#								mounter ${2} ${DEVNODE} ${3}/${DEVNODE}
+#							else
+								echo ${DEVNODE}
+#							fi
+						done
+					fi
+				;;
+			esac
+		;;
+		*)
+			echo "usage:"
+		;;
+	esac
+}
 old_mounter $*
 
 
