* Add trackfile based file verification support.
* Add the quiet/verbose OPTIONS, and make sure they are checked before output is sent.

diff --git a/trunk/src/share/bin/verify b/trunk/src/share/bin/verify
--- a/trunk/src/share/bin/verify
+++ b/trunk/src/share/bin/verify
@@ -86,22 +86,40 @@ verify_loop() {
 					# We always need the file's hash from the contents, so keep it out
 					# of the conditional
 					RHASH=$(${type} -q "${1}" 2>${DEVICES}/null)
-					if [ "${RTRACKFILE}" = "" ] ; then
+					if [ "${RTRACKFILE}" != "" ]; then
+						if [ "${WRITE}" = "yes" ] ; then
+							echo "F:${1}:${RHASH}:$(stat -f '%z' "${1}")"							
+						else
+							unset FHASH
+							FHASH=$(grep -a ^F: "${RTRACKFILE}" | awk -v FILENAME="${1}" -F ":" '{ if ($2 == FILENAME) { print $3; } }' 2>${DEVICES}/null)
+							if [ "${RHASH}" != "${FHASH}" ] ; then
+								if [ "${QUIET}" = "no" ] ; then
+									echo "${type} fail ${1}"
+								fi
+								ERRORCODE="65"
+							else
+								if [ "${QUIET}" = "no" ] ; then
+									echo "${type} pass ${1}"
+								fi
+							fi	
+						fi
+					else
 						if [ "${WRITE}" = "yes" ] ; then
 							setextattr system ${type} ${RHASH} "${1}" 2>${DEVICES}/null
 						else
 							unset FHASH
-							if [ "${FHASH}" = "" ] ; then
-								FHASH=$(getextattr -q system ${type} "${1}" 2>${DEVICES}/null)
-							fi
+							FHASH=$(getextattr -q system ${type} "${1}" 2>${DEVICES}/null)
 							if [ "${RHASH}" != "${FHASH}" ] ; then
-								echo "${type} fail ${1}"					
+								if [ "${QUIET}" = "no" ] ; then
+									echo "${type} fail ${1}"
+								fi
+								ERRORCODE="65"
 							else
-								echo "${type} pass ${1}"
+								if [ "${QUIET}" = "no" ] ; then
+									echo "${type} pass ${1}"
+								fi
 							fi	
 						fi
-					else
-						echo "F:${1}:${RHASH}:$(stat -f '%z' "${1}")"
 					fi
 				done
 			;;	
@@ -111,34 +129,68 @@ verify_loop() {
 }
 
 verify() {
+	ERRORCODE="0"
+	QUIET="no"
+	WRITE="no"
+	RECURSE="yes"
+
+	if [ "${OPTIONS}" != "" ] ; then
+		for option in ${OPTIONS}
+		do
+			case "${option}" in
+				norecurse)
+					RECURSE="no"
+				;;
+				recurse)
+					RECURSE="yes"
+				;;
+				quiet)
+					QUIET="yes"
+				;;
+				verbose)
+					QUIET="no"
+				;;
+				write)
+					WRITE="yes"
+				;;
+				nowrite)
+					WRITE="no"
+				;;
+			esac
+		done
+	fi
+
 	SCRATCHDIR="${TMPDIR}/verify/$(dd if=/dev/random bs=4m count=1 2>/dev/null | sha256 -q)"
 	mkdir -p "${SCRATCHDIR}"
 	TYPES="sha256 md5"
 
 	if [ "${RTRACKFILE}" != "" ] ; then
 		TYPES="sha256"
-		TRACKDATA="$(verify_loop $@)"
-		TRACKDATA="$(printf "${TRACKDATA}\n#")"
-		echo "${TRACKDATA}" | dd bs=512 fillchar=" " conv=sync "of=${SCRATCHDIR}/head" 2>${DEVICES}/null
-		dd if=/dev/zero bs=512 count=1 "of=${SCRATCHDIR}/tail" 2>${DEVICES}/null
+		if [ "${WRITE}" = "yes" ] ; then
+			TRACKDATA="$(verify_loop $@)"
+			TRACKDATA="$(printf "${TRACKDATA}\n#")"
+			echo "${TRACKDATA}" | dd bs=512 fillchar=" " conv=sync "of=${SCRATCHDIR}/head" 2>${DEVICES}/null
+			dd if=/dev/zero bs=512 count=1 "of=${SCRATCHDIR}/tail" 2>${DEVICES}/null
 
-		if [ -r "${TRACKFILE_PRIVATE_KEY}" ] ; then
-			sha256 -q "${SCRATCHDIR}/head" | openssl rsautl -sign -inkey "${TRACKFILE_PRIVATE_KEY}" -out "${SCRATCHDIR}/sign" 2>${DEVICES}/null
+			if [ -r "${TRACKFILE_PRIVATE_KEY}" ] ; then
+				sha256 -q "${SCRATCHDIR}/head" | openssl rsautl -sign -inkey "${TRACKFILE_PRIVATE_KEY}" -out "${SCRATCHDIR}/sign" 2>${DEVICES}/null
+			else
+				dd if=/dev/zero bs=512 count=1 "of=${SCRATCHDIR}/sign" 2>${DEVICES}/null
+			fi
+
+			cat "${SCRATCHDIR}/head" "${SCRATCHDIR}/sign" "${SCRATCHDIR}/tail" >"${SCRATCHDIR}/trackfile"
+			DEVICE="$(mdconfig -af ${SCRATCHDIR}/trackfile)"
+			geom label load
+			geom label label trackfile /dev/${DEVICE}
+			mdconfig -d -u $(echo ${DEVICE} | cut -b 3-7)
+			cp "${SCRATCHDIR}/trackfile" "${TRACKFILE}"
 		else
-			dd if=/dev/zero bs=512 count=1 "of=${SCRATCHDIR}/sign" 2>${DEVICES}/null
+			verify_loop $@
 		fi
-
-		cat "${SCRATCHDIR}/head" "${SCRATCHDIR}/sign" "${SCRATCHDIR}/tail" >"${SCRATCHDIR}/trackfile"
-		DEVICE="$(mdconfig -af ${SCRATCHDIR}/trackfile)"
-		geom label load
-		geom label label trackfile /dev/${DEVICE}
-		mdconfig -d -u $(echo ${DEVICE} | cut -b 3-7)
-		cp "${SCRATCHDIR}/trackfile" "${TRACKFILE}"
 	else
 		verify_loop $@
 	fi
-
-
+	exit "${ERRORCODE}"
 }
 
 verify $@
