Merge /trunk/src r561 to /branches/releases/0.1/R1/src
Flesh out the issue commit type.

AQA from MFRT Run number: 579f44fe-2663-4f78-9bed-5a01320a6965

* Change the comment stripping logic. This one doesn't result in half the services file being missing on the image. 

Edited wiki page through web user interface.

* Add a conditional to update and make sure we can fetch the mirrorlist (and throw a network connection error, as it's hosted on google, and if google is unavailable, it's most likely network related).

* Add a conditional to update and make sure we can fetch the destination trackfile (if it doesn't exist, we throw a ${VERSION} doesn't exist on this mirror, and bail out, for now; will add a mirror recursing logic later).

* Add src/share/lib/services. This is identical to the freebsd /etc/services, phttpget needs it.

diff --git a/0.1/R1/src/share/bin/update b/0.1/R1/src/share/bin/update
--- a/0.1/R1/src/share/bin/update
+++ b/0.1/R1/src/share/bin/update
@@ -234,6 +234,9 @@ real_update() {
 			echo "Trackfile is corrupted"
 			exit "${ERRORCODE}"
 		fi
+	else
+		echo "${VERSION} does not seem to exist on this mirror"
+		exit 65
 	fi
 
 	cd "${DESTDIR}/evoke/"
@@ -276,7 +279,7 @@ real_update() {
 				PDESTDIR="${STAGEDIR}/$(dirname ${FILENAME})"
 				BASENAME="$(basename ${FILENAME})"
 				PPATCHDIR="${PATCHDIR}/${HASH}"
-				PDOWNDIR="${SCRATCHDIR}/download/${HASH}"
+				PDOWNDIR="${DOWNDIR}/${HASH}"
 				mkdir -p "${PPATCHDIR}"
 				mkdir -p "${PDESTDIR}"
 				mkdir -p "${PDOWNDIR}"
@@ -389,11 +392,17 @@ update() {
 	mkdir -p "${STAGEDIR}"
 	PATCHDIR="${SCRATCHDIR}/patch"
 	mkdir -p "${PATCHDIR}"
+	DOWNDIR="${SCRATCHDIR}/download"
+	mkdir -p "${DOWNDIR}"
 
 	cd "${TEMPDIR}"
 
 	if [ "${EVOKE_UPDATE_MIRROR}" = "" ] ; then
 		phttpget evoke.googlecode.com /svn/info/mirrorlist 2>${DEVICES}/null
+		if [ ! -f mirrorlist ] ; then
+			echo "Unable to fetch mirrorlist, Network connection down?"
+			exit 65
+		fi
 		EVOKE_UPDATE_MIRROR="$(grep -v ^# ${TEMPDIR}/mirrorlist | grep -v ^$ | grep ^http:// | head -n 1)"
 	fi
 
@@ -407,7 +416,7 @@ update() {
 			fi
 		;;
 	esac
-	rm -r ${SCRATCHDIR}
+#	rm -r ${SCRATCHDIR}
 }
 
 update $@
