Merge /trunk/src r589 to /branches/releases/0.1/R1/src
r589 (heliocentric) {

	* Disable 6.x, and re-enable 7.x, and make sure the recent changes work.

}

r588 (heliocentric) {

	* Fix some of the output.

}

r587 (heliocentric) {

	* Fix a typo where the public key wasn't going into the shared directory.

}

r586 (heliocentric) {

	* Fix a logic bug in create-updates.

	* Remove the extra boot code copying routine, dynamic.sh handles it for us.

}

r585 (heliocentric) {

	AQA from MFRT run number: 6514316b-06a1-4204-a56a-61046cd4088d

	* fix the bug in the boot code. This will probably be abi dependent.

}

r584 (heliocentric) {

	AQA from MFRT run number: 6514316b-06a1-4204-a56a-61046cd4088d

	* Let's just build no-op patches.

}

r583 (heliocentric) {

	* Add a (commented out) assignment of the timestamp. Note, that this is only meant for update's use, and before it is added it must not use the date as it does in the example. It must use the commit date from svn. This will replace an 'stat -f %m' check in update, which may not be a proper course of action.

}

r582 (heliocentric) {

	* Reverse the sort order, so the timestamps descend. We should always check the most recently installed versions first.

}

r581 (heliocentric) {

	* Fix the error message stub for update, by actually checking the error code.

}

r580 (heliocentric) {

	* Add the missing parts of update, to call fetch_full_files if there is no source versions available.

	* Remove linker.hints from the kernel directory. It's not necessary, and it breaks updating as the file is erroneously the wrong permissions.

}

r579 (heliocentric) {

	* Fix a bug where RETVAL was propogating past find_mirror and breaking the update program.

	* Add verbose messages for patch downloading.

	* Fix the detection code for if no version exists on the destination directory, and make sure we create the directories before cd'ing to them, just in case they don't exist.

}

r578 (heliocentric) {

	* Remove the create_updates as it is broken.

	* update now respects verbose, and generates some verbose output for each step. Useful for debugging.

}

diff --git a/branches/releases/0.1/R1/src/share/bin/update b/branches/releases/0.1/R1/src/share/bin/update
--- a/branches/releases/0.1/R1/src/share/bin/update
+++ b/branches/releases/0.1/R1/src/share/bin/update
@@ -49,131 +49,6 @@ if [ ! -d "${TMPDIR}" ] ; then
 	TMPDIR="/tmp"
 fi
 
-create_updates() {
-	if [ "${1}" = "" ] ; then
-		echo "Error: No version set"
-		exit 5
-	fi
-
-	DESTDIR="${1}"
-
-	shift
-
-	DEST="${1}"
-
-
-	BINUPDIR="${RELEASEDIR}/evoke/BIN-UPDATES"
-	DECOMDIR="${SCRATCHDIR}/decom"
-	export TESTDIR="${SCRATCHDIR}/test"
-	export PATCHDIR="${SCRATCHDIR}/patch"
-
-	if [ -d "${PATCHDIR}" ] ; then
-		rm -r "${PATCHDIR}"
-	fi
-
-	if [ ! -f "${DESTDIR}/trackfile" ] ; then
-		echo "Destination does not exist"
-		exit 3
-	else
-		TRACKFILE="${DESTDIR}/trackfile" OPTIONS="quiet" verify
-		ERRORCODE=$?
-		if [ "${ERRORCODE}" != "0" ] ; then
-			DEST_TRACKFILE="$(grep -a ^F: ${DESTDIR}/trackfile)"
-		else
-			echo "Destination Integrity check failed"
-			exit 3
-		fi
-	fi
-
-	IFS="${FORFS}"
-
-
-	shift
-	while [ "${1}" != "" ] 
-	do
-		SOURCE="${1}"
-		echo "${SOURCE}"
-		SOURCEDIR="${RELEASEDIR}/evoke/${SOURCE}"
-		if [ ! -f "${SOURCEDIR}/trackfile" ] ; then
-			echo "Source does not exist"
-		else
-			TRACKFILE="${SOURCEDIR}/trackfile" OPTIONS="quiet" verify
-			ERRORCODE=$?
-			if [ "${ERRORCODE}" != "0" ] ; then
-				SOURCE_TRACKFILE="$(grep -a ^F: ${SOURCEDIR}/trackfile)"
-			else
-				echo "Source Integrity check failed"
-				break
-			fi
-			for filespec in ${DEST_TRACKFILE}
-			do
-				FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
-				DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
-				SOURCEFILE="${SOURCEDIR}/${FILENAME}"
-				DESTFILE="${DESTDIR}/${FILENAME}"
-				if [ -f "${SOURCEFILE}" ] ; then
-					SOURCEHASH="$(echo "${SOURCE_TRACKFILE}" | grep ${FILENAME} | cut -d : -f 3)"
-					REALHASH="$(sha256 -q "${SOURCEFILE}")"
-					if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
-						if [ "${SOURCEHASH}" != "${DESTHASH}" ] ; then
-							case "${SOURCEFILE}" in
-								*.gz)
-									mkdir -p "${DECOMDIR}"
-									gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
-									RFILE="${DECOMDIR}/${SOURCEHASH}"
-								;;
-								*)
-									RFILE="${SOURCEFILE}"
-								;;
-							esac
-	
-							case "${DESTFILE}" in
-								*.gz)
-									mkdir -p "${DECOMDIR}"
-									gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
-									DFILE="${DECOMDIR}/${DESTHASH}"
-								;;
-								*)
-									DFILE="${DESTFILE}"
-								;;
-							esac
-
-							PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
-							mkdir -p ${PATCHDIR}/${DESTHASH}/
-							bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
-							mkdir -p "${TESTDIR}"
-							bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
-							case "${DESTFILE}" in
-								*.gz)
-									mkdir -p "${DECOMDIR}"
-									rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
-									gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
-									mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
-								;;
-								*.bz2)
-								;;
-								*)
-									RFILE="${FILENAME}"
-								;;
-							esac
-							REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
-							if [ "${REALHASH}" != "${DESTHASH}" ] ; then
-								echo "Patch failed"
-								exit 4
-							fi
-						fi
-					fi
-				fi
-			done
-		fi
-		shift
-	done
-
-	mkdir -p "${BINUPDIR}/${DEST}"
-
-	cd "${PATCHDIR}" && tar -cf - * | tar -xvpf - -C "${BINUPDIR}/${DEST}" 2>/dev/null >/dev/null
-}
-
 apply_patch() {
 	PATCHFILE="${1}"
 	SOURCEFILE="${2}"
@@ -226,6 +101,7 @@ real_update() {
 	find_mirror "evoke/${VERSION}/trackfile" "${TEMPDIR}/trackfile"
 	TRACKFILE="${TEMPDIR}/trackfile" OPTIONS="quiet" verify
 	ERRORCODE="$?"
+
 	if [ "${ERRORCODE}" = 0 ] ; then
 		DEST_TRACKFILE="$(grep -a ^F: ${TEMPDIR}/trackfile)"
 	else
@@ -234,6 +110,7 @@ real_update() {
 	fi
 
 	DEST_TRACKFILE="$(grep -a ^F: ${TEMPDIR}/trackfile)"
+	mkdir -p "${DESTDIR}/evoke/"
 	cd "${DESTDIR}/evoke/"
 
 	VERSIONLIST="$(for version in $(echo */*/trackfile) 
@@ -243,111 +120,170 @@ real_update() {
 			;;
 			ISO-IMAGES/*)
 			;;
+			\*/\*/trackfile)
+				echo "error"
+			;;
 			*)
 				echo "$(stat -f '%m' "${version}"):$(dirname ${version})"
 			;;
 		esac
-	done | sort | cut -d : -f 2)"
+	done | sort -r | cut -d : -f 2)"
 
 	# Let's find out how many bytes we have to download.
 	BYTECOUNT="$(echo "${DEST_TRACKFILE}" | awk -F ":" '{ SUM += $4; } END { print SUM; }')"
 	MB="$((${BYTECOUNT} / 1000 / 1000))"
-	echo "The update utility will attempt to keep the total size of files downloaded to a minimum, "
-	echo "where possible."
-	echo ""
-	echo "In the worst case, update will download ${BYTECOUNT} bytes (~ ${MB}MB)"
-	read -p "Continue? [Y/n]: " PROMPT
+	if [ "${VERBOSE}" = "NO" ] ; then
+		echo "The update utility will attempt to keep the total size of files downloaded to a minimum, "
+		echo "where possible."
+		echo ""
+		echo "In the worst case, update will download ${BYTECOUNT} bytes (~ ${MB}MB)"
+		read -p "Continue? [Y/n]: " PROMPT
+	else
+		PROMPT="y"
+	fi
 	case "${PROMPT}" in
 		[nN])
 		;;
 		*)
 			# No reference points? Just fetch!
-			for filespec in ${DEST_TRACKFILE}
-			do
-
-				cd "${DESTDIR}/evoke/"
-				# let's see if HASH matches any already existing file.
-
-				HASH="$(echo "${filespec}" | cut -d ":" -f 3)"
-				FILENAME="$(echo "${filespec}" | cut -d ":" -f 2)"
-				PDESTDIR="${STAGEDIR}/$(dirname ${FILENAME})"
-				BASENAME="$(basename ${FILENAME})"
-				PPATCHDIR="${PATCHDIR}/${HASH}"
-				PDOWNDIR="${DOWNDIR}/${HASH}"
-				mkdir -p "${PPATCHDIR}"
-				mkdir -p "${PDESTDIR}"
-				mkdir -p "${PDOWNDIR}"
-
-				for version in ${VERSIONLIST}
+			if [ "${VERSIONLIST}" = "error" ] ; then
+				for filespec in ${DEST_TRACKFILE}
 				do
-					MATCHED_LINE="$(grep -a ^F: "${DESTDIR}/evoke/${version}/trackfile" | grep ${HASH})"
-					if [ "${MATCHED_LINE}" != "" ] ; then
-						SFILENAME="$(echo ${MATCHED_LINE} | cut -d ":" -f 2)"
-						cp "${DESTDIR}/evoke/${version}/${SFILENAME}" "${STAGEDIR}/${FILENAME}"
-						sh -c "cd ${STAGEDIR} && TRACKFILE="${TEMPDIR}/trackfile" OPTIONS="quiet" verify "${FILENAME}""
-						RETVAL=$?
-						if [ "${RETVAL}" = "0" ] ; then
-							break
-						fi
+					unset RETVAL
+					cd "${DESTDIR}/evoke/"
+
+					vecho "Starting ${FILENAME} \{\n"
+					vecho "\tFetching full files \{\n"
+
+					HASH="$(echo "${filespec}" | cut -d ":" -f 3)"
+					FILENAME="$(echo "${filespec}" | cut -d ":" -f 2)"
+					PDESTDIR="${STAGEDIR}/$(dirname ${FILENAME})"
+					BASENAME="$(basename ${FILENAME})"
+					mkdir -p "${PDESTDIR}"
+					vecho "\tHASH=${HASH}\n"
+					vecho "\tFILENAME=${FILENAME}\n"
+					vecho "\tPDESTDIR=${PDESTDIR}\n"
+					vecho "\tBASENAME=${BASENAME}\n"
+
+
+					RETVAL="$(fetch_full_file "${HASH}" "${FILENAME}" "${PDESTDIR}" "${BASENAME}")" 2>&1
+
+					if [ "${RETVAL}" != "0" ] ; then
+						unset RETVAL
+						echo "File corrupted in transit, bailing out"
+						exit 65
+					else
+						unset RETVAL
 					fi
 				done
-
-				if [ "${RETVAL}" = "0" ] ; then
-					unset RETVAL
-					continue
-				else
-					unset RETVAL
-				fi
-
-				HASHLIST="$(for version in ${VERSIONLIST}
+			else
+				for filespec in ${DEST_TRACKFILE}
 				do
-					FILEHASH="$(grep -a ^F: ${DESTDIR}/evoke/${version}/trackfile | cut -d : -f 3)"
-					if [ "${FILEHASH}" != "" ] ; then
-						for filehash in ${FILEHASH}
-						do
-							echo "${FILESPEC}/evoke/BIN-UPDATES/${VERSION}/${HASH}/${filehash}" 
-						done
-					fi
-				done)"
-				if [ "${HASHLIST}" != "" ] ; then
-					cd "${PPATCHDIR}"
-					for hash in ${HASHLIST}
+
+					unset RETVAL
+					cd "${DESTDIR}/evoke/"
+					# let's see if HASH matches any already existing file.
+
+					HASH="$(echo "${filespec}" | cut -d ":" -f 3)"
+					FILENAME="$(echo "${filespec}" | cut -d ":" -f 2)"
+					PDESTDIR="${STAGEDIR}/$(dirname ${FILENAME})"
+					BASENAME="$(basename ${FILENAME})"
+					PPATCHDIR="${PATCHDIR}/${HASH}"
+					mkdir -p "${PPATCHDIR}"
+					mkdir -p "${PDESTDIR}"
+					vecho "Starting ${FILENAME} \{\n"
+					vecho "\tChecking existing files \{\n"
+
+					for version in ${VERSIONLIST}
 					do
-						phttpget "${SERVER}" ${hash} 2>${DEVICES}/null
-						realhash="$(basename ${hash})"
-						if [ -f "${realhash}" ] ; then
-							FILE="$(grep -Ha ^F: ${DESTDIR}/evoke/*/*/trackfile | grep ${realhash} | awk -F : '{ FILENAME=$3; "dirname " $1 | getline; print $0 "/" FILENAME; }' | head -n 1)"
-							RETVAL="$(apply_patch "${realhash}" "${FILE}" "${PDESTDIR}/${BASENAME}" "${realhash}" "${HASH}")"
+						MATCHED_LINE="$(grep -a ^F: "${DESTDIR}/evoke/${version}/trackfile" | grep ${HASH})"
+						if [ "${MATCHED_LINE}" != "" ] ; then
+							SFILENAME="$(echo ${MATCHED_LINE} | cut -d ":" -f 2)"
+							FILEPATH="${DESTDIR}/evoke/${version}/${SFILENAME}"
+							vecho "\t\t${FILEPATH} {\n"
+							cp "${FILEPATH}" "${STAGEDIR}/${FILENAME}"
+							sh -c "cd ${STAGEDIR} && TRACKFILE="${TEMPDIR}/trackfile" OPTIONS="quiet" verify "${FILENAME}""
+							RETVAL=$?
 							if [ "${RETVAL}" = "0" ] ; then
+								vecho "\t\t\t$Verification passed\n\t\t}\n"
 								break
+							else
+								vecho "\t\t\tVerification failed\n\t\t}\n"
+	
 							fi
 						fi
 					done
-				fi
+	
+					vecho "\t}\n"
+					if [ "${RETVAL}" = "0" ] ; then
+						unset RETVAL
+						vecho "}\n"
+						continue
+					else
+						unset RETVAL
+					fi
 
-				if [ "${RETVAL}" = "0" ] ; then
-					unset RETVAL
-					continue
-				else
-					unset RETVAL
-				fi
+					vecho "\tGrabbing patches {\n"
+					HASHLIST="$(for version in ${VERSIONLIST}
+					do
+						FILEHASH="$(grep -a ^F: ${DESTDIR}/evoke/${version}/trackfile | cut -d : -f 3)"
+						if [ "${FILEHASH}" != "" ] ; then
+							for filehash in ${FILEHASH}
+							do
+								echo "${FILESPEC}/evoke/BIN-UPDATES/${VERSION}/${HASH}/${filehash}" 
+							done
+						fi
+					done)"
+					if [ "${HASHLIST}" != "" ] ; then
+						cd "${PPATCHDIR}"
+						for hash in ${HASHLIST}
+						do
+							realhash="$(basename ${hash})"
+							vecho "\t\tFetching ${realhash} {\n"
+							phttpget "${SERVER}" ${hash} 2>${DEVICES}/null
+							if [ -f "${realhash}" ] ; then
+								vecho "\t\t\tFile exists: ${realhash}\n"
+								FILE="$(grep -Ha ^F: ${DESTDIR}/evoke/*/*/trackfile | grep ${realhash} | awk -F : '{ FILENAME=$3; "dirname " $1 | getline; print $0 "/" FILENAME; }' | head -n 1)"
+								RETVAL="$(apply_patch "${realhash}" "${FILE}" "${PDESTDIR}/${BASENAME}" "${realhash}" "${HASH}")"
+								if [ "${RETVAL}" = "0" ] ; then
+									vecho "\t\t\tPatch applied successfully: ${realhash}\n"
+									vecho "\t\t}\n"
+									break
+								else
+									vecho "\t\t\tPatch did not apply: ${realhash}\n"
+									vecho "\t\t}\n"
+								fi
+							else
+								vecho "\t\t\tFile doesn't exist: ${realhash}\n"
+								vecho "\t\t}\n"
+							fi
+						done
+					fi
 
-				# Ok, fall back on grabbing the file.
-				cd "${PDOWNDIR}"
-				phttpget "${SERVER}" "${FILESPEC}/evoke/${VERSION}/${FILENAME}" 2>${DEVICES}/null
-				cp "${BASENAME}" "${PDESTDIR}/"
-				cd "${STAGEDIR}"
-				TRACKFILE="${TEMPDIR}/trackfile" OPTIONS="quiet" verify "${FILENAME}"
-				RETVAL=$?
-				if [ "${RETVAL}" != "0" ] ; then
-					unset RETVAL
-					echo "File corrupted in transit, bailing out"
-					exit 65
-				else
-					unset RETVAL
-				fi
-			done
+					vecho "\t}\n"
+					if [ "${RETVAL}" = "0" ] ; then
+						unset RETVAL
+						vecho "}\n"
+						continue
+					else
+						unset RETVAL
+					fi
 
+					vecho "\tGrabbing full file {\n"
+					# Ok, fall back on grabbing the file.
+					RETVAL="$(fetch_full_file "${HASH}" "${FILENAME}" "${PDESTDIR}" "${BASENAME}")"
+	
+					vecho "\t}\n"
+					if [ "${RETVAL}" != "0" ] ; then
+						unset RETVAL
+						echo "File corrupted in transit, bailing out"
+						exit 65
+					else
+						unset RETVAL
+					fi
+					vecho "}\n"
+				done
+			fi
 			cd "${STAGEDIR}"
 
 			FILELIST="$(echo ${DEST_TRACKFILE} | cut -d : -f 2)"
@@ -375,6 +311,35 @@ real_update() {
 		;;
 	esac
 }
+
+fetch_full_file() {
+	local HASH="${1}"
+	local FILENAME="${2}"
+	local PDESTDIR="${3}"
+	local BASENAME="${4}"
+	
+	local PDOWNDIR="${DOWNDIR}/${HASH}"
+	mkdir -p "${PDOWNDIR}"
+
+	cd "${PDOWNDIR}"
+	vecho "\t\tFetching ${FILENAME} {\n" 1>&2
+	phttpget "${SERVER}" "${FILESPEC}/evoke/${VERSION}/${FILENAME}" 2>${DEVICES}/null
+
+	cp "${BASENAME}" "${PDESTDIR}/"
+	cd "${STAGEDIR}"
+
+	TRACKFILE="${TEMPDIR}/trackfile" OPTIONS="quiet" verify "${FILENAME}"
+	local ERRORCODE="$?"
+	if [ "${ERRORCODE}" = "0" ] ; then
+		vecho "\t\t\tFile fetched successfully\n" 1>&2
+	else
+		vecho "\t\t\tError! file not found.\n" 1>&2
+	fi
+	vecho "\t\t}\n" 1>&2
+
+	echo "${ERRORCODE}"
+}
+
 
 find_mirror() {
 	FILENAME="${1}"
@@ -407,6 +372,13 @@ find_mirror() {
 		echo "No usable mirrors found. Bailing out."
 		exit 65
 	fi
+	unset RETVAL
+}
+
+vecho() {
+	if [ "${VERBOSE}" = "YES" ] ; then
+		printf "$@"
+	fi
 }
 
 update() {
@@ -433,11 +405,26 @@ update() {
 		echo "${EVOKE_UPDATE_MIRROR}" >${TEMPDIR}/mirrorlist
 	fi
 
+	VERBOSE="NO"
+
+	if [ "${OPTIONS}" != "" ] ; then
+		for option in ${OPTIONS}
+		do
+			case "${option}" in
+				verbose)
+					VERBOSE="YES"
+				;;
+				quiet)
+					VERBOSE="NO"
+				;;
+			esac
+		done
+	fi
 
 	case "${1}" in
 		install)
 			if [ "${3}" != "" ] ; then
-				real_update "${2}" "${3}"
+				real_update "${2}" "${3}" 2>&1
 			fi
 		;;
 	esac
