Merge /trunk/src r576 to /branches/releases/0.1/R1/src
r576 (heliocentric) {

	* Fix some glaring logic bugs in create-updates. These include testing for a != condition when we should have been testing for =, and other serious issues. For some reason, I did not see the conditional correctly on my screen. I may need to see a doctor.

	* At least now, the create-updates script will work again.

}

r575 (heliocentric) {

	Edited wiki page through web user interface.

}

r574 (heliocentric) {

	AQA from MFRT run number: 612d47ad-a86a-45a1-b944-8c87e0a26107

	* Add basename to the image

	* Add support to mounter to call a fsck binary if it is available or applicable.

}

r573 (heliocentric) {

	* Fix a bug where there wasn't a newline in the log message after the description.

}

diff --git a/branches/releases/0.1/R1/src/builder/create-updates b/branches/releases/0.1/R1/src/builder/create-updates
--- a/branches/releases/0.1/R1/src/builder/create-updates
+++ b/branches/releases/0.1/R1/src/builder/create-updates
@@ -27,12 +27,25 @@
 FORFS="
 "
 
-if [ ! -d "${RELEASEDIR}" ] ; then
-	RELEASEDIR="/releases"
+OLDFS=" 	
+"
+
+if [ ! -c "${DEVICES}/null" ] ; then
+	if [ -c "/dev/null" ] ; then
+		DEVICES=/dev
+	else
+		echo "Error, no device nodes found"
+		exit 1
+	fi
 fi
 
 if [ ! -d "${STAGEDIR}" ] ; then
-	STAGEDIR="/tmp/stagedir"
+	STAGEDIR="/tmp/$(dd if=${DEVICES}/random bs=1m count=1 2>${DEVICES}/null | sha256 -q)/stagedir"
+	mkdir -p "${STAGEDIR}"
+fi
+
+if [ ! -d "${RELEASEDIR}" ] ; then
+	RELEASEDIR="/releases"
 fi
 
 if [ "${1}" = "" ] ; then
@@ -47,22 +60,27 @@ shift
 DESTDIR="${1}"
 
 
-BINUPDIR="${RELEASEDIR}/evoke/BIN-UPDATES"
-DECOMDIR="${STAGEDIR}/decom"
-TESTDIR="${STAGEDIR}/test"
-PATCHDIR="${STAGEDIR}/patch"
-
 if [ -d "${PATCHDIR}" ] ; then
 	rm -r "${PATCHDIR}"
 fi
+
+BINUPDIR="${RELEASEDIR}/evoke/BIN-UPDATES"
+mkdir -p "${BINUPDIR}"
+DECOMDIR="${STAGEDIR}/decom"
+mkdir -p "${DECOMDIR}"
+TESTDIR="${STAGEDIR}/test"
+mkdir -p "${TESTDIR}"
+PATCHDIR="${STAGEDIR}/patch"
+mkdir -p "${PATCHDIR}"
+
 
 if [ ! -f "${DESTDIR}/trackfile" ] ; then
 	echo "Destination does not exist"
 	exit 3
 else
-	TRACKFILE="${DESTDIR}/trackfile" verify
-	ERRORCODE=$?
-	if [ "${ERRORCODE}" != "0" ] ; then
+	OPTIONS="quiet" TRACKFILE="${DESTDIR}/trackfile" verify
+	ERRORCODE="$?"
+	if [ "${ERRORCODE}" = "0" ] ; then
 		DEST_TRACKFILE="$(grep -a ^F: ${DESTDIR}/trackfile)"
 	else
 		echo "Destination Integrity check failed"
@@ -70,90 +88,93 @@ else
 	fi
 fi
 
-IFS="${FORFS}"
-
-
 shift
-while [ "${1}" != "" ] 
-do
-	SOURCE="${1}"
-	echo "${SOURCE}"
-	SOURCEDIR="${RELEASEDIR}/evoke/${SOURCE}"
-	if [ ! -f "${SOURCEDIR}/trackfile" ] ; then
-		echo "Source does not exist"
-	else
-		TRACKFILE="${SOURCEDIR}/trackfile" verify
-		ERRORCODE=$?
-		if [ "${ERRORCODE}" != "0" ] ; then
-			SOURCE_TRACKFILE="$(grep -a ^F: ${SOURCEDIR}/trackfile)"
+
+
+if [ "${1}" != "" ] ; then
+	while [ "${1}" != "" ] 
+	do
+		SOURCE="${1}"
+		SOURCEDIR="${RELEASEDIR}/evoke/${SOURCE}"
+		echo "${SOURCEDIR}"
+		if [ ! -f "${SOURCEDIR}/trackfile" ] ; then
+			echo "Source does not exist"
 		else
-			echo "Source Integrity check failed"
-			break
-		fi
-		for filespec in ${DEST_TRACKFILE}
-		do
-			FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
-			DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
-			SOURCEFILE="${SOURCEDIR}/${FILENAME}"
-			DESTFILE="${DESTDIR}/${FILENAME}"
-			if [ -f "${SOURCEFILE}" ] ; then
-				SOURCEHASH="$(echo "${SOURCE_TRACKFILE}" | grep ${FILENAME} | cut -d : -f 3)"
-				REALHASH="$(sha256 -q "${SOURCEFILE}")"
-				if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
-					if [ "${SOURCEHASH}" != "${DESTHASH}" ] ; then
-						case "${SOURCEFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
-								RFILE="${DECOMDIR}/${SOURCEHASH}"
-							;;
-							*)
-								RFILE="${SOURCEFILE}"
-							;;
-						esac
+			TRACKFILE="${SOURCEDIR}/trackfile" verify
+			ERRORCODE="$?"
+			if [ "${ERRORCODE}" = "0" ] ; then
+				SOURCE_TRACKFILE="$(grep -a ^F: ${SOURCEDIR}/trackfile)"
+			else
+				echo "Source Integrity check failed"
+				break
+			fi
+			IFS="${FORFS}"
+			for filespec in ${DEST_TRACKFILE}
+			do
+				FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
+				DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
+				SOURCEFILE="${SOURCEDIR}/${FILENAME}"
+				DESTFILE="${DESTDIR}/${FILENAME}"
+				if [ -f "${SOURCEFILE}" ] ; then
+					SOURCEHASH="$(echo "${SOURCE_TRACKFILE}" | grep ${FILENAME} | cut -d : -f 3)"
+					REALHASH="$(sha256 -q "${SOURCEFILE}")"
+					if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
+						if [ "${SOURCEHASH}" != "${DESTHASH}" ] ; then
+							case "${SOURCEFILE}" in
+								*.gz)
+									mkdir -p "${DECOMDIR}"
+									gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
+									RFILE="${DECOMDIR}/${SOURCEHASH}"
+								;;
+								*)
+									RFILE="${SOURCEFILE}"
+								;;
+							esac
 
-						case "${DESTFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
-								DFILE="${DECOMDIR}/${DESTHASH}"
-							;;
-							*)
-								DFILE="${DESTFILE}"
-							;;
-						esac
+							case "${DESTFILE}" in
+								*.gz)
+									mkdir -p "${DECOMDIR}"
+									gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
+									DFILE="${DECOMDIR}/${DESTHASH}"
+								;;
+								*)
+									DFILE="${DESTFILE}"
+								;;
+							esac
 
-						PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
-						mkdir -p ${PATCHDIR}/${DESTHASH}/
-						bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
-						mkdir -p "${TESTDIR}"
-						bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
-						case "${DESTFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
-								gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
-								mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
-							;;
-							*.bz2)
-							;;
-							*)
-								RFILE="${FILENAME}"
-							;;
-						esac
-						REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
-						if [ "${REALHASH}" != "${DESTHASH}" ] ; then
-							echo "Patch failed"
-							exit 4
+							PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
+							mkdir -p ${PATCHDIR}/${DESTHASH}/
+							bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
+							mkdir -p "${TESTDIR}"
+							bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
+							case "${DESTFILE}" in
+								*.gz)
+									mkdir -p "${DECOMDIR}"
+									rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
+									gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
+									mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
+								;;
+								*.bz2)
+								;;
+								*)
+									RFILE="${FILENAME}"
+								;;
+							esac
+							REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
+							if [ "${REALHASH}" != "${DESTHASH}" ] ; then
+								echo "Patch failed"
+								exit 4
+							fi
 						fi
 					fi
 				fi
-			fi
-		done
-	fi
-	shift
-done
+			done
+			IFS="${OLDFS}"
+		fi
+		shift
+	done
 
-mkdir -p "${BINUPDIR}/${DEST}"
+	mkdir -p "${BINUPDIR}/${DEST}"
 
-cd "${PATCHDIR}" && tar -cf - * | tar -xvpf - -C "${BINUPDIR}/${DEST}" 2>/dev/null >/dev/null
+	cd "${PATCHDIR}" && tar -cf - * | tar -xvpf - -C "${BINUPDIR}/${DEST}" 2>/dev/null >/dev/null
+fi
