Merge /trunk r702:710 to /branches/releases/0.1/r1
r710 (heliocentric) {

	* Port builds are fixed.

}

r709 (heliocentric) {

	* Add mounter support to update. Now any filesystem that mounter supports, is supported by update as a mirror, this 

	includes ftp, ssh, nfs, cds, other disks, remounting, the whole gamut. Note that there is no ui for this yet.

}

r708 (heliocentric) {

	* Add tftp support to the fetching routines.

}

r707 (heliocentric) {

	* Replace the grep with a loop, so we can use multiple source files from each version.

}

r706 (heliocentric) {

	* Write a trackfile to the BIN-UPDATES so we can get a list of source hashes and make smarter choices on the patch files.

}

r705 (heliocentric) {

	* Add a conditional to compare the size of the resulting patch file, if it is greater then or equal to the full size of the file, don't bother adding it.

}

r704 (heliocentric) {

	* oops, remove the hardcoded shared object.

}

r703 (heliocentric) {

	* Add a check-libs tool.

}

diff --git a/0.1/r1/builder/create-updates b/0.1/r1/builder/create-updates
--- a/0.1/r1/builder/create-updates
+++ b/0.1/r1/builder/create-updates
@@ -40,7 +40,7 @@ if [ ! -c "${DEVICES}/null" ] ; then
 fi
 
 if [ ! -d "${STAGEDIR}" ] ; then
-	STAGEDIR="/tmp/$(dd if=${DEVICES}/random bs=1m count=1 2>${DEVICES}/null | sha256 -q)/stagedir"
+	STAGEDIR="/tmp/update/$(dd if=${DEVICES}/random bs=1m count=1 2>${DEVICES}/null | sha256 -q)/stagedir"
 	mkdir -p "${STAGEDIR}"
 fi
 
@@ -97,12 +97,11 @@ if [ "${1}" != "" ] ; then
 	do
 		SOURCE="${1}"
 		SOURCEDIR="${RELEASEDIR}/evoke/${SOURCE}"
-		echo "${SOURCEDIR}"
 		if [ ! -f "${SOURCEDIR}/trackfile" ] ; then
 			echo "Source does not exist"
 		else
 			cd "${SOURCEDIR}"
-			TRACKFILE="${SOURCEDIR}/trackfile" verify
+			OPTIONS="quiet" TRACKFILE="${SOURCEDIR}/trackfile" verify
 			ERRORCODE="$?"
 			if [ "${ERRORCODE}" = "0" ] ; then
 				SOURCE_TRACKFILE="$(grep -a ^F: ${SOURCEDIR}/trackfile)"
@@ -115,66 +114,95 @@ if [ "${1}" != "" ] ; then
 			do
 				FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
 				DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
-				SOURCEFILE="${SOURCEDIR}/${FILENAME}"
+				DESTSIZE="$(echo "${filespec}" | cut -d : -f 4)"
 				DESTFILE="${DESTDIR}/${FILENAME}"
-				if [ -f "${SOURCEFILE}" ] ; then
-					SOURCEHASH="$(echo "${SOURCE_TRACKFILE}" | grep ${FILENAME} | cut -d : -f 3)"
-					REALHASH="$(sha256 -q "${SOURCEFILE}")"
-					if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
-						case "${SOURCEFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
-								RFILE="${DECOMDIR}/${SOURCEHASH}"
-							;;
-							*)
-								RFILE="${SOURCEFILE}"
-							;;
-						esac
+				
+				SOURCE_FILESPEC_LIST="$(echo "${SOURCE_TRACKFILE}" | grep "^F:${FILENAME}")"
 
-						case "${DESTFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
-								DFILE="${DECOMDIR}/${DESTHASH}"
-							;;
-							*)
-								DFILE="${DESTFILE}"
-							;;
-						esac
-
-						PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
-						mkdir -p ${PATCHDIR}/${DESTHASH}/
-						bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
-						mkdir -p "${TESTDIR}"
-						bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
-						case "${DESTFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
-								gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
-								mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
-							;;
-							*.bz2)
-							;;
-							*)
-								RFILE="${FILENAME}"
-							;;
-						esac
-						REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
-						if [ "${REALHASH}" != "${DESTHASH}" ] ; then
-							echo "Patch failed"
-							exit 4
+				for source_filespec in ${SOURCE_FILESPEC_LIST}
+				do
+					SOURCEFILE="${SOURCEDIR}/$(echo "${source_filespec}" | cut -d ":" -f 2)"
+					SOURCEHASH="$(echo "${source_filespec}" | cut -d ":" -f 3)"
+					if [ -f "${SOURCEFILE}" ] ; then
+						REALHASH="$(sha256 -q "${SOURCEFILE}")"
+						if [ "${REALHASH}" = "${SOURCEHASH}" ] ; then
+							case "${SOURCEFILE}" in
+								*.gz)
+									mkdir -p "${DECOMDIR}"
+									gunzip -9nc "${SOURCEFILE}" >"${DECOMDIR}/${SOURCEHASH}"
+									RFILE="${DECOMDIR}/${SOURCEHASH}"
+								;;
+								*)
+									RFILE="${SOURCEFILE}"
+								;;
+							esac
+	
+							case "${DESTFILE}" in
+								*.gz)
+									mkdir -p "${DECOMDIR}"
+									gunzip -9nc "${DESTFILE}" >"${DECOMDIR}/${DESTHASH}"
+									DFILE="${DECOMDIR}/${DESTHASH}"
+								;;
+								*)
+									DFILE="${DESTFILE}"
+								;;
+							esac
+	
+							PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
+							mkdir -p ${PATCHDIR}/${DESTHASH}/
+							bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
+							PATCHSIZE="$(stat -f '%z' ${PATCHFILE})"
+							if [ "${PATCHSIZE}" -ge "${DESTSIZE}" ] ; then
+								rm "${PATCHFILE}"
+							else
+								mkdir -p "${TESTDIR}"
+								bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"	
+								case "${DESTFILE}" in
+									*.gz)
+										mkdir -p "${DECOMDIR}"
+										rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null	
+										gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
+										mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
+									;;
+									*.bz2)
+									;;
+									*)
+									RFILE="${FILENAME}"
+									;;
+								esac
+								REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
+								if [ "${REALHASH}" != "${DESTHASH}" ] ; then
+									echo "Patch failed"
+									exit 4
+								fi
+							fi
 						fi
 					fi
-				fi
+				done
 			done
 		fi
 		IFS="${OLDFS}"
 		shift
 	done
 
-	mkdir -p "${BINUPDIR}/${DEST}"
+	# Generate a trackfile for supporting http without webdav, and tftp.
 
+	for filespec in ${DEST_TRACKFILE}
+	do
+		DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
+		DESTPATH="${PATCHDIR}/${DESTHASH}"
+		if [ -d "${DESTPATH}" ] ; then
+			cd "${DESTPATH}"
+			HASHFILELIST="$(echo *)"
+			if [ "${HASHFILELIST}" != "" -a "${HASHFILELIST}" != "*" ] ; then
+				OPTIONS="write quiet" TRACKFILE="${TESTDIR}/${DESTHASH}" verify ${HASHFILELIST}
+				mv ${TESTDIR}/${DESTHASH} ${DESTPATH}/trackfile
+			fi
+		fi
+	done
+
+	mkdir -p "${BINUPDIR}/${DEST}"
 	cd "${PATCHDIR}" && tar -cf - * | tar -xvpf - -C "${BINUPDIR}/${DEST}" 2>/dev/null >/dev/null
 fi
+
+rm -r "${STAGEDIR}"
