* Add a conditional to compare the size of the resulting patch file, if it is greater then or equal to the full size of the file, don't bother adding it.

diff --git a/trunk/builder/create-updates b/trunk/builder/create-updates
--- a/trunk/builder/create-updates
+++ b/trunk/builder/create-updates
@@ -97,12 +97,11 @@ if [ "${1}" != "" ] ; then
 	do
 		SOURCE="${1}"
 		SOURCEDIR="${RELEASEDIR}/evoke/${SOURCE}"
-		echo "${SOURCEDIR}"
 		if [ ! -f "${SOURCEDIR}/trackfile" ] ; then
 			echo "Source does not exist"
 		else
 			cd "${SOURCEDIR}"
-			TRACKFILE="${SOURCEDIR}/trackfile" verify
+			OPTIONS="quiet" TRACKFILE="${SOURCEDIR}/trackfile" verify
 			ERRORCODE="$?"
 			if [ "${ERRORCODE}" = "0" ] ; then
 				SOURCE_TRACKFILE="$(grep -a ^F: ${SOURCEDIR}/trackfile)"
@@ -115,6 +114,7 @@ if [ "${1}" != "" ] ; then
 			do
 				FILENAME="$(echo "${filespec}" | cut -d : -f 2)"
 				DESTHASH="$(echo "${filespec}" | cut -d : -f 3)"
+				DESTSIZE="$(echo "${filespec}" | cut -d : -f 4)"
 				SOURCEFILE="${SOURCEDIR}/${FILENAME}"
 				DESTFILE="${DESTDIR}/${FILENAME}"
 				if [ -f "${SOURCEFILE}" ] ; then
@@ -146,25 +146,30 @@ if [ "${1}" != "" ] ; then
 						PATCHFILE="${PATCHDIR}/${DESTHASH}/${SOURCEHASH}"
 						mkdir -p ${PATCHDIR}/${DESTHASH}/
 						bsdiff "${RFILE}" "${DFILE}" "${PATCHFILE}"
-						mkdir -p "${TESTDIR}"
-						bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
-						case "${DESTFILE}" in
-							*.gz)
-								mkdir -p "${DECOMDIR}"
-								rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
-								gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
-								mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
-							;;
-							*.bz2)
-							;;
-							*)
+						PATCHSIZE="$(stat -f '%z' ${PATCHFILE})"
+						if [ "${PATCHSIZE}" -ge "${DESTSIZE}" ] ; then
+							rm "${PATCHFILE}"
+						else
+							mkdir -p "${TESTDIR}"
+							bspatch "${RFILE}" "${TESTDIR}/${DESTHASH}" "${PATCHFILE}"
+							case "${DESTFILE}" in
+								*.gz)
+									mkdir -p "${DECOMDIR}"
+									rm "${TESTDIR}/${DESTHASH}.gz" 2>/dev/null 1>/dev/null
+									gzip -9nc "${TESTDIR}/${DESTHASH}" >"${TESTDIR}/${DESTHASH}.gz"
+									mv "${TESTDIR}/${DESTHASH}.gz" "${TESTDIR}/${DESTHASH}"
+								;;
+								*.bz2)
+								;;
+								*)
 								RFILE="${FILENAME}"
-							;;
-						esac
-						REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
-						if [ "${REALHASH}" != "${DESTHASH}" ] ; then
-							echo "Patch failed"
-							exit 4
+								;;
+							esac
+							REALHASH="$(sha256 -q "${TESTDIR}/${DESTHASH}")"
+							if [ "${REALHASH}" != "${DESTHASH}" ] ; then
+								echo "Patch failed"
+								exit 4
+							fi
 						fi
 					fi
 				fi
@@ -175,6 +180,5 @@ if [ "${1}" != "" ] ; then
 	done
 
 	mkdir -p "${BINUPDIR}/${DEST}"
-
 	cd "${PATCHDIR}" && tar -cf - * | tar -xvpf - -C "${BINUPDIR}/${DEST}" 2>/dev/null >/dev/null
 fi
